00:00:00.005933 main     VirtualBox COM Server 7.0.6 r155176 win.amd64 (Jan 11 2023 16:38:38) release log
00:00:00.005936 main     Log opened 2023-02-23T01:20:31.302852600Z
00:00:00.005937 main     Build Type: release
00:00:00.005947 main     OS Product: Windows 11
00:00:00.005948 main     OS Release: 10.0.22000
00:00:00.005949 main     OS Service Pack: 
00:00:00.057639 main     DMI Product Name: HP ENVY Laptop 13-ad0xx
00:00:00.079825 main     DMI Product Version: Type1ProductConfigId
00:00:00.079839 main     Firmware type: UEFI
00:00:00.080435 main     Secure Boot: VERR_PRIVILEGE_NOT_HELD
00:00:00.080471 main     Host RAM: 8036MB (7.8GB) total, 4563MB (4.4GB) available
00:00:00.080478 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.080479 main     Process ID: 11108
00:00:00.080480 main     Package type: WINDOWS_64BITS_GENERIC
00:00:00.281791          VirtualBox: object creation starts
00:00:00.282138          Home directory: 'C:\Users\ruthe\.VirtualBox'
00:00:00.282305          Installed Drivers:
00:00:00.349196            C:\Windows\system32\DRIVERS\VBoxNetLwf.sys (Version: 7.0.6.5176)
00:00:00.463541            C:\Windows\system32\DRIVERS\VBoxUSBMon.sys (Version: 7.0.6.5176)
00:00:00.528106            C:\Windows\system32\DRIVERS\VBoxNetAdp6.sys (Version: 7.0.6.5176)
00:00:00.545421          Loading settings file "C:\Users\ruthe\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.551634          usbLibGetDevices: Starting USB device enumeration
00:00:00.553031          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
00:00:00.553191          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 8
00:00:00.556580          usbLibGetDevices: Found 3 USB devices, 0 captured
00:00:00.556653          USB: Unknown USB device detected (idVendor: 0x04f2, idProduct: 0xb5ed)
00:00:00.556722          USB: Unknown USB device detected (idVendor: 0x1ea7, idProduct: 0x0064)
00:00:00.556775          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0a2a)
00:00:00.882414          HostDnsMonitor: initializing
00:00:00.895608          HostDnsMonitor: updating information
00:00:00.895639          HostDnsMonitor: old information
00:00:00.895640            no server entries
00:00:00.895642            no domain set
00:00:00.895642            no search string entries
00:00:00.895643          HostDnsMonitor: new information
00:00:00.895644            server 1: 192.168.1.1
00:00:00.895645            domain: bbrouter
00:00:00.895646            no search string entries
00:00:01.089778          VD: VDInit finished with VINF_SUCCESS
00:00:01.323877 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:00:01.573303 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
00:00:01.573422 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 8
00:00:01.577401 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:00:01.809689          Loading settings file "C:\Users\ruthe\VirtualBox VMs\ubunto\ubunto.vbox" with version "1.16-windows"
00:00:01.819167          Loading settings file "C:\Users\ruthe\VirtualBox VMs\mvwin\mvwin.vbox" with version "1.19-windows"
00:00:01.828804          Loading settings file "C:\Users\ruthe\VirtualBox VMs\mvwin2\mvwin2.vbox" with version "1.19-windows"
00:00:01.838707          Loading settings file "C:\Users\ruthe\VirtualBox VMs\mvwin3\mvwin3.vbox" with version "1.19-windows"
00:00:01.989955          OCI: Local config file 'C:\Users\ruthe\.VirtualBox\oci_config' does not exist
00:00:01.990233          OCI: Original config file 'C:\Users\ruthe\.oci\config' does not exist
00:00:01.990236          OCI: Reading profiles finished with status ERROR_SUCCESS
00:00:01.990288          ExtPack: Created cloud provider 'OCI' (hrc=ERROR_SUCCESS)
00:00:01.990612          VirtualBox: object created
00:00:02.161298          Saving settings file "C:\Users\ruthe\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:02.383395          Finished saving settings file "C:\Users\ruthe\.VirtualBox\VirtualBox.xml"
00:00:02.383826          Saving settings file "C:\Users\ruthe\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:02.400449          Finished saving settings file "C:\Users\ruthe\.VirtualBox\VirtualBox.xml"
00:00:02.401322          Saving settings file "C:\Users\ruthe\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:02.408192          Finished saving settings file "C:\Users\ruthe\.VirtualBox\VirtualBox.xml"
00:00:14.954073          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine is not mutable (state is PoweredOff)}, preserve=false aResultDetail=0
00:00:20.158109          Launched VM: 756657248 pid: 13552 (0x34f0) frontend: GUI/Qt name: mvwin
00:00:21.006948          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine is not mutable (state is PoweredOff)}, preserve=false aResultDetail=0
00:00:47.029338 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:00:47.030892 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
00:00:47.032039 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 8
00:00:47.032353 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:01:20.658402 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:01:20.659718 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
00:01:20.659941 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&e688183&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 8
00:01:20.660429 USBPROXY usbLibGetDevices: Found 3 USB devices, 0 captured
00:05:51.562772 main     VirtualBox: object deletion starts
00:05:51.563126 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\ruthe\VirtualBox VMs\ubunto\ubunto.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:05:51.565729 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\ruthe\VirtualBox VMs\mvwin\mvwin.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:05:51.568417 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\ruthe\VirtualBox VMs\mvwin2\mvwin2.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:05:51.570273 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\ruthe\VirtualBox VMs\mvwin3\mvwin3.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:05:51.577450 main     HostDnsMonitor: shutting down ...
00:05:51.577718 main     HostDnsMonitor: shut down
00:05:51.587877 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={7682d5eb-f00e-44f1-8ca2-99d08b1cd607} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:05:51.595526 main     VirtualBox: object deleted
